In [1]:
#load python packages
import os
import pandas as pd
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
#print out current directory
os.getcwd()

'C:\\Users\\Pranay\\Projects\\GitHub\\Practice\\Guided-Capstone_Updated'

In [2]:
#path = '/Users/hitesh.hinduja/Downloads/capstone-01-master/data/processed'
#print(os.listdir(path))
#os.chdir(path)

df = pd.read_csv('data/step3_output.csv',)
df.head()

state                           Name  summit_elev  vertical_drop  \
0      Alaska               Hilltop Ski Area         2090            294   
1     Arizona            Sunrise Park Resort        11100           1800   
2  California  Yosemite Ski & Snowboard Area         7800            600   
3  California         Boreal Mountain Resort         7700            500   
4  California                    Dodge Ridge         8200           1600   

   trams  fastEight  fastSixes  fastQuads  quad  triple  ...  \
0      0        0.0          0          0     0       1  ...   
1      0        0.0          0          1     2       3  ...   
2      0        0.0          0          0     0       1  ...   
3      0        0.0          0          1     1       3  ...   
4      0        0.0          0          0     1       2  ...   

   SkiableTerrain_ac  Snow Making_ac  daysOpenLastYear  yearsOpen  \
0               30.0       30.000000        150.000000       36.0   
1              800.0       80.000000        115.000000       49.0   
2               88.0      475.882353        110.000000       84.0   
3              380.0      200.000000        150.000000       54.0   
4              862.0      475.882353        152.111111       69.0   

   averageSnowfall  AdultWeekday  AdultWeekend  projectedDaysOpen  \
0             69.0          30.0     34.000000              152.0   
1            250.0          74.0     78.000000              104.0   
2            300.0          47.0     47.000000              107.0   
3            400.0          49.0     81.416667              150.0   
4            350.0          78.0     78.000000              140.0   

   NightSkiing_ac  clusters  
0            30.0         1  
1            80.0         0  
2             0.0         0  
3           200.0         0  
4             0.0         0  

[5 rows x 26 columns]

In [3]:
df.drop('AdultWeekday', axis=1, inplace=True)

In [4]:
dfo=df[['state']] # select object type columns and then deselect name
print(dfo.head())

df1 = pd.concat([df.drop(dfo, axis=1), pd.get_dummies(dfo)], axis=1)

print(df1.info())

        state
0      Alaska
1     Arizona
2  California
3  California
4  California
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 59 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Name                  176 non-null    object 
 1   summit_elev           176 non-null    int64  
 2   vertical_drop         176 non-null    int64  
 3   trams                 176 non-null    int64  
 4   fastEight             176 non-null    float64
 5   fastSixes             176 non-null    int64  
 6   fastQuads             176 non-null    int64  
 7   quad                  176 non-null    int64  
 8   triple                176 non-null    int64  
 9   double                176 non-null    int64  
 10  surface               176 non-null    int64  
 11  total_chairs          176 non-null    int64  
 12  Runs                  176 non-null    float64
 13  TerrainParks          176 non-null    flo

In [5]:
df2 = df.drop('state',axis=1)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Name               176 non-null    object 
 1   summit_elev        176 non-null    int64  
 2   vertical_drop      176 non-null    int64  
 3   trams              176 non-null    int64  
 4   fastEight          176 non-null    float64
 5   fastSixes          176 non-null    int64  
 6   fastQuads          176 non-null    int64  
 7   quad               176 non-null    int64  
 8   triple             176 non-null    int64  
 9   double             176 non-null    int64  
 10  surface            176 non-null    int64  
 11  total_chairs       176 non-null    int64  
 12  Runs               176 non-null    float64
 13  TerrainParks       176 non-null    float64
 14  LongestRun_mi      176 non-null    float64
 15  SkiableTerrain_ac  176 non-null    float64
 16  Snow Making_ac     176 non

In [6]:
df3 = df.drop(['state','summit_elev','vertical_drop','averageSnowfall','yearsOpen','daysOpenLastYear','projectedDaysOpen'], axis=1)
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Name               176 non-null    object 
 1   trams              176 non-null    int64  
 2   fastEight          176 non-null    float64
 3   fastSixes          176 non-null    int64  
 4   fastQuads          176 non-null    int64  
 5   quad               176 non-null    int64  
 6   triple             176 non-null    int64  
 7   double             176 non-null    int64  
 8   surface            176 non-null    int64  
 9   total_chairs       176 non-null    int64  
 10  Runs               176 non-null    float64
 11  TerrainParks       176 non-null    float64
 12  LongestRun_mi      176 non-null    float64
 13  SkiableTerrain_ac  176 non-null    float64
 14  Snow Making_ac     176 non-null    float64
 15  AdultWeekend       176 non-null    float64
 16  NightSkiing_ac     176 non

In [7]:
# first we import the preprocessing package from the sklearn library
from sklearn import preprocessing

# Declare an explanatory variable, called X,and assign it the result of dropping 'Name' and 'AdultWeekend' from the df
X1 = df1.drop(['Name','AdultWeekend'], axis=1)

# Declare a response variable, called y, and assign it the AdultWeekend column of the df 
y = df.loc[:,'AdultWeekend']

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler = preprocessing.StandardScaler().fit(X1)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled1 = scaler.transform(X1) 
X_scaled1

array([[-0.49238543, -0.93659084,  0.        , ..., -0.13168538,
        -0.25819889, -0.17099639],
       [ 2.298836  ,  1.63287582,  0.        , ..., -0.13168538,
        -0.25819889, -0.17099639],
       [ 1.27652405, -0.41450797,  0.        , ..., -0.13168538,
        -0.25819889, -0.17099639],
       ...,
       [ 1.27900238,  1.24216675,  0.        , ..., -0.13168538,
        -0.25819889,  5.84807661],
       [ 1.85366561,  0.25089176,  0.        , ..., -0.13168538,
        -0.25819889,  5.84807661],
       [ 1.8031696 ,  0.43856861,  0.        , ..., -0.13168538,
        -0.25819889,  5.84807661]])

In [8]:
# Declare an explanatory variable, called X,and assign it the result of dropping 'Name' and 'AdultWeekend' from the df
X2 = df2.drop(['Name','AdultWeekend'], axis=1)

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler = preprocessing.StandardScaler().fit(X2)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled2 = scaler.transform(X2) 
X_scaled2

array([[-0.49238543, -0.93659084,  0.        , ...,  1.91224903,
        -0.30088859,  0.62994079],
       [ 2.298836  ,  1.63287582,  0.        , ..., -0.32287717,
         0.75951174, -1.58745079],
       [ 1.27652405, -0.41450797,  0.        , ..., -0.18318178,
        -0.93712879, -1.58745079],
       ...,
       [ 1.27900238,  1.24216675,  0.        , ...,  0.56186028,
         1.39575193, -1.58745079],
       [ 1.85366561,  0.25089176,  0.        , ...,  0.23590438,
        -0.93712879, -1.58745079],
       [ 1.8031696 ,  0.43856861,  0.        , ...,  0.23590438,
        -0.93712879, -1.58745079]])

In [9]:
# Declare an explanatory variable, called X,and assign it the result of dropping 'Name' and 'AdultWeekend' from the df
X3 = df3.drop(['Name','AdultWeekend'], axis=1)

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler = preprocessing.StandardScaler().fit(X3)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled3 = scaler.transform(X3) 
X_scaled3

array([[ 0.        ,  0.        ,  0.        , ..., -0.86158761,
        -0.30088859,  0.62994079],
       [ 0.        ,  0.        ,  0.        , ..., -0.32780981,
         0.75951174, -1.58745079],
       [ 0.        ,  0.        ,  0.        , ...,  3.89845435,
        -0.93712879, -1.58745079],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  1.48703468,
         1.39575193, -1.58745079],
       [ 0.        ,  0.        ,  0.        , ..., -0.86158761,
        -0.93712879, -1.58745079],
       [ 0.        ,  0.        ,  0.        , ..., -0.06092092,
        -0.93712879, -1.58745079]])

In [10]:
from sklearn.model_selection import train_test_split

# Get the 1-dimensional flattened array of our response variable y by calling the ravel() function on y
y = y.ravel()

In [11]:
# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train1, X_test1, y_train1, y_test1 = train_test_split(X_scaled1, y, test_size=0.25, random_state=1)

In [12]:
# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train2, X_test2, y_train2, y_test2 = train_test_split(X_scaled2, y, test_size=0.25, random_state=1)

In [13]:
# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train3, X_test3, y_train3, y_test3 = train_test_split(X_scaled3, y, test_size=0.25, random_state=1)

In [14]:
# all first model set
from sklearn import linear_model
from sklearn.metrics import explained_variance_score,mean_absolute_error

lm = linear_model.LinearRegression()
model = lm.fit(X_train1,y_train1)

In [15]:
# Make a variable called y_pred and assign it the result of calling predict() on our model variable with parameter X_test
y_pred1 = model.predict(X_test1)

In [16]:
# You might want to use the explained_variance_score() and mean_absolute_error() metrics.
# You can plug y_test and y_pred into the functions to evaluate the model
explained_variance_score(y_test1, y_pred1)

-8.578442595947218e+16

In [17]:
mean_absolute_error(y_test1, y_pred1)

651301151.8291173

In [ ]:
lm.intercept_

In [19]:
y_pred1

array([ 4.84214377e+01,  6.91143087e+01,  7.07844748e+01,  4.15088400e+01,
        5.30242209e+01,  4.55442404e+01,  4.93483175e+01,  7.89348654e+01,
        4.40544943e+01,  4.73807882e+01,  8.59675802e+01,  8.64153341e+01,
        4.54136252e+01,  5.99636740e+01,  5.07610373e+01,  5.95769552e+01,
        9.89758810e+01,  3.65696310e+01,  5.37366232e+01,  4.56900534e+01,
        5.82043966e+01,  4.69520163e+01,  5.84775900e+01,  6.05383810e+01,
        4.28357443e+01,  7.44529318e+01,  3.64736837e+01,  3.51834005e+01,
        6.98301291e+01,  6.05500998e+01,  6.19844259e+01,  8.85407003e+01,
        9.42659201e+01,  6.18831076e+01,  4.85471701e+01,  7.10300802e+01,
       -2.86572502e+10,  7.98586935e+01,  7.71067404e+01,  5.48889669e+01,
        4.54775290e+01,  3.26575216e+01,  7.63635763e+01,  3.11337179e+01])