In [2]:
#load python packages
import os
import pandas as pd
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
#print out current directory
os.getcwd()

'/Users/hitesh.hinduja/Downloads'

In [3]:
path = '/Users/hitesh.hinduja/Downloads/capstone-01-master/data/processed'
print(os.listdir(path))
os.chdir(path)

df = pd.read_csv('step3_output.csv',)
df.head()

['step2_output.csv', 'step3_output.csv']


Name    state  summit_elev  vertical_drop  trams  fastEight  \
0       Alyeska Resort   Alaska         3939           2500      1          0   
1  Eaglecrest Ski Area   Alaska         2600           1540      0          0   
2     Hilltop Ski Area   Alaska         2090            294      0          0   
3     Arizona Snowbowl  Arizona        11500           2300      0          0   
4  Sunrise Park Resort  Arizona        11100           1800      0          0   

   fastSixes  fastQuads  quad  triple  ...  SkiableTerrain_ac  Snow Making_ac  \
0          0          2     2       0  ...             1610.0           113.0   
1          0          0     0       0  ...              640.0            60.0   
2          0          0     0       1  ...               30.0            30.0   
3          1          0     2       2  ...              777.0           104.0   
4          0          1     2       3  ...              800.0            80.0   

   daysOpenLastYear  yearsOpen  averageSnowfall  AdultWeekday  AdultWeekend  \
0               150         60            669.0          65.0          85.0   
1                45         44            350.0          47.0          53.0   
2               150         36             69.0          30.0          34.0   
3               122         81            260.0          89.0          89.0   
4               115         49            250.0          74.0          78.0   

   projectedDaysOpen  NightSkiing_ac  clusters  
0                150           550.0         0  
1                 90             0.0         0  
2                152            30.0         0  
3                122             0.0         1  
4                104            80.0         1  

[5 rows x 26 columns]

In [4]:
df.drop('AdultWeekday', axis=1, inplace=True)

In [5]:
dfo=df[['state']] # select object type columns and then deselect name
print(dfo.head())

df1 = pd.concat([df.drop(dfo, axis=1), pd.get_dummies(dfo)], axis=1)

print(df1.info())

     state
0   Alaska
1   Alaska
2   Alaska
3  Arizona
4  Arizona
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 59 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Name                  330 non-null    object 
 1   summit_elev           330 non-null    int64  
 2   vertical_drop         330 non-null    int64  
 3   trams                 330 non-null    int64  
 4   fastEight             330 non-null    int64  
 5   fastSixes             330 non-null    int64  
 6   fastQuads             330 non-null    int64  
 7   quad                  330 non-null    int64  
 8   triple                330 non-null    int64  
 9   double                330 non-null    int64  
 10  surface               330 non-null    int64  
 11  total_chairs          330 non-null    int64  
 12  Runs                  330 non-null    int64  
 13  TerrainParks          330 non-null    int64  
 14  LongestR

In [6]:
df2 = df.drop('state',axis=1)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Name               330 non-null    object 
 1   summit_elev        330 non-null    int64  
 2   vertical_drop      330 non-null    int64  
 3   trams              330 non-null    int64  
 4   fastEight          330 non-null    int64  
 5   fastSixes          330 non-null    int64  
 6   fastQuads          330 non-null    int64  
 7   quad               330 non-null    int64  
 8   triple             330 non-null    int64  
 9   double             330 non-null    int64  
 10  surface            330 non-null    int64  
 11  total_chairs       330 non-null    int64  
 12  Runs               330 non-null    int64  
 13  TerrainParks       330 non-null    int64  
 14  LongestRun_mi      330 non-null    float64
 15  SkiableTerrain_ac  330 non-null    float64
 16  Snow Making_ac     330 non

In [7]:
df3 = df.drop(['state','summit_elev','vertical_drop','averageSnowfall','yearsOpen','daysOpenLastYear','projectedDaysOpen'], axis=1)
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Name               330 non-null    object 
 1   trams              330 non-null    int64  
 2   fastEight          330 non-null    int64  
 3   fastSixes          330 non-null    int64  
 4   fastQuads          330 non-null    int64  
 5   quad               330 non-null    int64  
 6   triple             330 non-null    int64  
 7   double             330 non-null    int64  
 8   surface            330 non-null    int64  
 9   total_chairs       330 non-null    int64  
 10  Runs               330 non-null    int64  
 11  TerrainParks       330 non-null    int64  
 12  LongestRun_mi      330 non-null    float64
 13  SkiableTerrain_ac  330 non-null    float64
 14  Snow Making_ac     330 non-null    float64
 15  AdultWeekend       330 non-null    float64
 16  NightSkiing_ac     330 non

In [8]:
# first we import the preprocessing package from the sklearn library
from sklearn import preprocessing

# Declare an explanatory variable, called X,and assign it the result of dropping 'Name' and 'AdultWeekend' from the df
X1 = df1.drop(['Name','AdultWeekend'], axis=1)

# Declare a response variable, called y, and assign it the AdultWeekend column of the df 
y = df.loc[:,'AdultWeekend']

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler = preprocessing.StandardScaler().fit(X1)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled1 = scaler.transform(X1) 
X_scaled1

array([[-0.1750243 ,  1.3572862 ,  1.4796585 , ..., -0.11076976,
        -0.22573306, -0.15762208],
       [-0.53401788,  0.34294523, -0.30893969, ..., -0.11076976,
        -0.22573306, -0.15762208],
       [-0.6707518 , -0.97358483, -0.30893969, ..., -0.11076976,
        -0.22573306, -0.15762208],
       ...,
       [ 0.86227679,  0.37569999, -0.30893969, ..., -0.11076976,
        -0.22573306,  6.34428877],
       [ 1.35961292, -0.23818762, -0.30893969, ..., -0.11076976,
        -0.22573306,  6.34428877],
       [ 1.31591169, -0.12196105, -0.30893969, ..., -0.11076976,
        -0.22573306,  6.34428877]])

In [9]:
# Declare an explanatory variable, called X,and assign it the result of dropping 'Name' and 'AdultWeekend' from the df
X2 = df2.drop(['Name','AdultWeekend'], axis=1)

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler = preprocessing.StandardScaler().fit(X2)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled2 = scaler.transform(X2) 
X_scaled2

array([[-1.75024298e-01,  1.35728620e+00,  1.47965850e+00, ...,
         1.04373424e+00,  5.28388759e+00, -7.36244575e-01],
       [-5.34017876e-01,  3.42945226e-01, -3.08939686e-01, ...,
        -1.04690187e+00, -6.09611897e-01, -7.36244575e-01],
       [-6.70751800e-01, -9.73584832e-01, -3.08939686e-01, ...,
         1.11342211e+00, -2.88148289e-01, -7.36244575e-01],
       ...,
       [ 8.62276787e-01,  3.75699987e-01, -3.08939686e-01, ...,
         1.02947990e-01,  5.69088000e-01,  1.35824430e+00],
       [ 1.35961292e+00, -2.38187625e-01, -3.08939686e-01, ...,
        -1.58381523e-03, -6.09611897e-01,  1.35824430e+00],
       [ 1.31591169e+00, -1.21961055e-01, -3.08939686e-01, ...,
        -1.58381523e-03, -6.09611897e-01,  1.35824430e+00]])

In [10]:
# Declare an explanatory variable, called X,and assign it the result of dropping 'Name' and 'AdultWeekend' from the df
X3 = df3.drop(['Name','AdultWeekend'], axis=1)

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler = preprocessing.StandardScaler().fit(X3)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled3 = scaler.transform(X3) 
X_scaled3

array([[ 1.4796585 , -0.05513178, -0.2840776 , ..., -0.1503032 ,
         5.28388759, -0.73624458],
       [-0.30893969, -0.05513178, -0.2840776 , ..., -0.36274889,
        -0.6096119 , -0.73624458],
       [-0.30893969, -0.05513178, -0.2840776 , ..., -0.48300117,
        -0.28814829, -0.73624458],
       ...,
       [-0.30893969, -0.05513178, -0.2840776 , ...,  0.39884887,
         0.569088  ,  1.3582443 ],
       [-0.30893969, -0.05513178, -0.2840776 , ..., -0.48300117,
        -0.6096119 ,  1.3582443 ],
       [-0.30893969, -0.05513178, -0.2840776 , ..., -0.60325344,
        -0.6096119 ,  1.3582443 ]])

In [11]:
from sklearn.model_selection import train_test_split

# Get the 1-dimensional flattened array of our response variable y by calling the ravel() function on y
y = y.ravel()

In [12]:
# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train1, X_test1, y_train1, y_test1 = train_test_split(X_scaled1, y, test_size=0.25, random_state=1)

In [13]:
# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train2, X_test2, y_train2, y_test2 = train_test_split(X_scaled2, y, test_size=0.25, random_state=1)

In [14]:
# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train3, X_test3, y_train3, y_test3 = train_test_split(X_scaled3, y, test_size=0.25, random_state=1)

In [15]:
# all first model set
from sklearn import linear_model
from sklearn.metrics import explained_variance_score,mean_absolute_error

lm = linear_model.LinearRegression()
model = lm.fit(X_train1,y_train1)

In [16]:
# Make a variable called y_pred and assign it the result of calling predict() on our model variable with parameter X_test
y_pred1 = model.predict(X_test1)

In [17]:
# You might want to use the explained_variance_score() and mean_absolute_error() metrics.
# You can plug y_test and y_pred into the functions to evaluate the model
explained_variance_score(y_test1, y_pred1)

0.3662666865074793

In [18]:
mean_absolute_error(y_test1, y_pred1)

13.763082588095843

In [19]:
lm.intercept_

64.27769116948181